Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "manager"
    config.vm.boot_timeout = 100000
    config.vm.network "private_network", ip: "192.168.1.2"
  
    config.vm.provider 'virtualbox' do |v|
      v.memory = 3072
    
    end
  
  
  end
  