---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: true

  vars:
    dbhost: "db01"
    dbname: "notes"
    dbusername: "notesapp"
    dbpassword: "devopsmaonamassa"

  tasks:
    - name: Configurar hosts lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items: 
        - 192.168.1.2 control-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01

    - name: Adicionar usuário do app
      user: 
        name: app
        comment: Usuário da aplicação
        uid: 500

    - name: Instalação do Maven
      apt: 
        name: maven
        state: latest

    - name: Instalação do Java 8
      apt: 
        name: openjdk-8-jdk
        state: latest

    - name: Criação do diretório de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    
    - name: Instalação do git client
      apt: 
        name: git
        state: latest
    
    - name: Clone do repositório Notes - app
      git: 
        repo: "https://github.com/andredw13L/spring-boot-mysql-rest-api-tutorial.git"
        dest: /opt/notes
        clone: yes
        force: yes
    
    - name: Configurar o arquivo de propriedades para o banco de dados
      template: 
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties

    - name: Gerar o pacote
      command: mvn -f /opt/notes.pom.xml package
      become_user: app 
