
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.ssh.insert_key = false

  config.vm.provision "shell", path: "provision.sh"

  config.vbguest.installer_options = {allow_kernel_upgrade: true}

end
