Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "jenkins"
  config.vm.boot_timeout = 100000
  config.vm.network "forwarded_port", guest: 8080, host: 8080, hostip: '127.0.0.1'
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider 'virtualbox' do |v|
    v.memory = 4096
  
  end


end
